-- Arquivo antigo desativado: o acesso somente por nome foi substituído por login com senha.
-- Execute supabase_setup.sql da pasta principal seguindo LEIA-ME-ATIVACAO.md.
-- Este arquivo não abre permissões públicas nem altera dados.
