-- 1. Crie NAMOITA em Authentication > Users (namoita@jessicmchdo.github.io), senha privada,
--    Auto Confirm User ativado. Faça isso ANTES de executar este arquivo.
-- 2. Execute o arquivo inteiro no SQL Editor. É uma transação: falhas revertem tudo.
-- 3. Execute supabase/agendar_multas.sql para ativar o processamento automático.
begin;
create schema if not exists faxinas_private;
revoke all on schema faxinas_private from public, anon;
grant usage on schema faxinas_private to authenticated, service_role;

create table if not exists public.faxina_perfis (
 user_id uuid primary key references auth.users(id) on delete cascade,
 pessoa text not null unique check (pessoa in ('JUKEBOX','LOTERYA','KOMIXÃO','NAMOITA','NAZARÉ','CAMILA','BAQUETADA','AMANDA','BELA'))
);
create table if not exists faxinas_private.convites (
 pessoa text primary key,
 token_hash text not null,
 expira_em timestamptz not null,
 usada_em timestamptz,
 liberada_por uuid not null references auth.users(id)
);
create table if not exists public.faxina_tarefas (
 id bigint generated by default as identity primary key,
 pessoa text not null check (pessoa in ('JUKEBOX','LOTERYA','KOMIXÃO','NAMOITA','NAZARÉ','CAMILA','BAQUETADA','AMANDA','BELA')),
 semana date not null check (semana >= date '2026-09-27' and extract(dow from semana)=0),
 bloco text not null check (bloco in ('dom_seg_ter','qui_sex_sab')),
 tarefa text not null check (btrim(tarefa)<>'' and upper(btrim(tarefa)) not in ('FOLGA','AUSENTE')),
 encerra_em timestamptz not null,
 estado text not null default 'pendente' check (estado in ('pendente','concluida','nao_concluida')),
 multa_valor numeric(10,2) not null default 0 check (multa_valor in (0,30)),
 alterada_em timestamptz,
 alterada_por uuid references auth.users(id) on delete set null,
 unique(semana,pessoa,bloco)
);
create index if not exists faxina_tarefas_pessoa_semana on public.faxina_tarefas(pessoa,semana);
create index if not exists faxina_tarefas_prazos on public.faxina_tarefas(encerra_em) where estado <> 'concluida';
create table if not exists faxinas_private.auditoria (
 id bigint generated always as identity primary key,
 tarefa_id bigint not null references public.faxina_tarefas(id),
 usuario_id uuid references auth.users(id) on delete set null,
 estado_anterior text not null,
 estado_novo text not null,
 alterada_em timestamptz not null default clock_timestamp()
);
alter table public.faxina_perfis enable row level security;
alter table public.faxina_tarefas enable row level security;
alter table faxinas_private.convites enable row level security;
alter table faxinas_private.auditoria enable row level security;
revoke all on public.faxina_perfis,public.faxina_tarefas from public,anon,authenticated;
revoke all on faxinas_private.convites,faxinas_private.auditoria from public,anon,authenticated;
grant select on public.faxina_perfis,public.faxina_tarefas to authenticated;

create or replace function faxinas_private.minha_pessoa() returns text
language sql stable security definer set search_path='' as $$
 select pessoa from public.faxina_perfis where user_id=auth.uid() and auth.uid() is not null
$$;
revoke all on function faxinas_private.minha_pessoa() from public,anon;
grant execute on function faxinas_private.minha_pessoa() to authenticated;
drop policy if exists faxina_perfil_leitura on public.faxina_perfis;
create policy faxina_perfil_leitura on public.faxina_perfis for select to authenticated
 using (user_id=(select auth.uid()) or (select faxinas_private.minha_pessoa())='NAMOITA');
drop policy if exists faxina_tarefa_leitura on public.faxina_tarefas;
create policy faxina_tarefa_leitura on public.faxina_tarefas for select to authenticated
 using (pessoa=(select faxinas_private.minha_pessoa()) or (select faxinas_private.minha_pessoa())='NAMOITA');

-- Só uma conta criada previamente pela administradora recebe o perfil NAMOITA.
-- O gatilho de cadastro abaixo não permite novos cadastros com esse nome.
do $$ declare v_id uuid; begin
 select id into v_id from auth.users where lower(email)='namoita@jessicmchdo.github.io' and email_confirmed_at is not null;
 if v_id is null then raise exception 'Crie primeiro a conta namoita@jessicmchdo.github.io no painel Authentication > Users, com Auto Confirm User ativado.'; end if;
 insert into public.faxina_perfis(user_id,pessoa) values(v_id,'NAMOITA') on conflict (user_id) do nothing;
 if not exists(select 1 from public.faxina_perfis where user_id=v_id and pessoa='NAMOITA') then raise exception 'A conta inicial já está vinculada a outro nome. Verifique os perfis.'; end if;
end $$;

create or replace function faxinas_private.email_da_pessoa(p_pessoa text) returns text
language sql immutable set search_path='' as $$
 select case p_pessoa when 'KOMIXÃO' then 'komixao' when 'NAZARÉ' then 'nazare'
 else lower(p_pessoa) end || '@jessicmchdo.github.io'
$$;
revoke all on function faxinas_private.email_da_pessoa(text) from public,anon,authenticated;

create or replace function faxinas_private.cadastrar_perfil() returns trigger
language plpgsql security definer set search_path='' as $$
declare v_pessoa text; v_convite faxinas_private.convites; v_codigo text;
begin
 -- Outros aplicativos deste projeto não recebem um perfil de faxinas.
 if lower(new.email) not like '%@jessicmchdo.github.io' then return new; end if;
 select nome into v_pessoa from unnest(array['JUKEBOX','LOTERYA','KOMIXÃO','NAMOITA','NAZARÉ','CAMILA','BAQUETADA','AMANDA','BELA']) nome
 where faxinas_private.email_da_pessoa(nome)=lower(new.email);
 if v_pessoa is null or v_pessoa='NAMOITA' then raise exception 'Cadastro não autorizado.'; end if;
 v_codigo:=btrim(coalesce(new.raw_user_meta_data->>'codigo_liberacao',''));
 select * into v_convite from faxinas_private.convites where pessoa=v_pessoa for update;
 if not found or v_convite.usada_em is not null or v_convite.expira_em<=clock_timestamp()
    or v_codigo='' or v_convite.token_hash<>encode(sha256(convert_to(v_codigo,'UTF8')),'hex') then
   raise exception 'Código de liberação inválido ou vencido.';
 end if;
 insert into public.faxina_perfis(user_id,pessoa) values(new.id,v_pessoa);
 update faxinas_private.convites set usada_em=clock_timestamp() where pessoa=v_pessoa;
 return new;
end $$;
revoke all on function faxinas_private.cadastrar_perfil() from public,anon,authenticated;
drop trigger if exists faxina_cadastro_autorizado on auth.users;
create trigger faxina_cadastro_autorizado after insert on auth.users for each row execute function faxinas_private.cadastrar_perfil();

create or replace function faxinas_private.liberar_acesso(p_pessoa text) returns text
language plpgsql security definer set search_path='' as $$
declare v_token text;
begin
 if auth.uid() is null or faxinas_private.minha_pessoa() is distinct from 'NAMOITA' then raise exception 'Somente NAMOITA pode liberar acessos.'; end if;
 if p_pessoa not in ('JUKEBOX','LOTERYA','KOMIXÃO','NAZARÉ','CAMILA','BAQUETADA','AMANDA','BELA') or p_pessoa is null then raise exception 'Nome inválido.'; end if;
 if exists(select 1 from public.faxina_perfis where pessoa=p_pessoa) then raise exception 'Esta pessoa já cadastrou sua senha.'; end if;
 v_token:=replace(gen_random_uuid()::text,'-','') || replace(gen_random_uuid()::text,'-','');
 insert into faxinas_private.convites(pessoa,token_hash,expira_em,usada_em,liberada_por)
 values(p_pessoa,encode(sha256(convert_to(v_token,'UTF8')),'hex'),clock_timestamp()+interval '7 days',null,auth.uid())
 on conflict(pessoa) do update set token_hash=excluded.token_hash,expira_em=excluded.expira_em,usada_em=null,liberada_por=excluded.liberada_por;
 return v_token;
end $$;
create or replace function public.faxina_liberar_acesso(p_pessoa text) returns text
language sql security invoker set search_path='' as $$select faxinas_private.liberar_acesso(p_pessoa)$$;

create or replace function faxinas_private.listar_acessos() returns jsonb
language plpgsql security definer set search_path='' as $$
begin
 if auth.uid() is null or faxinas_private.minha_pessoa() is distinct from 'NAMOITA' then raise exception 'Somente NAMOITA pode consultar acessos.'; end if;
 return (select jsonb_agg(jsonb_build_object('pessoa',nome,'cadastrada',p.user_id is not null,'convite_ativo',c.usada_em is null and c.expira_em>clock_timestamp()) order by nome)
 from unnest(array['JUKEBOX','LOTERYA','KOMIXÃO','NAMOITA','NAZARÉ','CAMILA','BAQUETADA','AMANDA','BELA']) nome
 left join public.faxina_perfis p on p.pessoa=nome left join faxinas_private.convites c on c.pessoa=nome);
end $$;
create or replace function public.faxina_listar_acessos() returns jsonb
language sql security invoker set search_path='' as $$select faxinas_private.listar_acessos()$$;

create or replace function faxinas_private.processar_vencidas(p_pessoa text default null) returns integer
language plpgsql security definer set search_path='' as $$
declare v_count integer;
begin
 update public.faxina_tarefas set estado='nao_concluida',multa_valor=30
 where encerra_em<=clock_timestamp() and estado<>'concluida' and (estado<>'nao_concluida' or multa_valor<>30)
 and (p_pessoa is null or pessoa=p_pessoa);
 get diagnostics v_count=row_count;return v_count;
end $$;
-- Não é concedida a usuários: cron/postgres fazem o processamento geral.
revoke all on function faxinas_private.processar_vencidas(text) from public,anon,authenticated;

create or replace function faxinas_private.listar() returns jsonb
language plpgsql security definer set search_path='' as $$
declare v_pessoa text;
begin
 v_pessoa:=faxinas_private.minha_pessoa();
 if auth.uid() is null or v_pessoa is null then raise exception 'Acesso não autorizado.'; end if;
 perform faxinas_private.processar_vencidas(case when v_pessoa='NAMOITA' then null else v_pessoa end);
 return coalesce((select jsonb_agg(jsonb_build_object(
 'id',id,'pessoa',pessoa,'semana',semana,'bloco',bloco,'tarefa',tarefa,'estado',estado,
 'estado_efetivo',case when encerra_em<=clock_timestamp() and estado<>'concluida' then 'nao_concluida' else estado end,
 'vencida',encerra_em<=clock_timestamp(),'prazo',encerra_em-interval '1 microsecond',
 'dia_vencimento',((encerra_em-interval '1 microsecond') at time zone 'America/Sao_Paulo')::date,
 'valor_multa',case when encerra_em<=clock_timestamp() and estado<>'concluida' then 30 else 0 end)
 order by semana desc,pessoa,bloco) from public.faxina_tarefas where pessoa=v_pessoa or v_pessoa='NAMOITA'),'[]'::jsonb);
end $$;
create or replace function public.faxina_listar() returns jsonb
language sql security invoker set search_path='' as $$select faxinas_private.listar()$$;

create or replace function faxinas_private.marcar(p_id bigint,p_estado text) returns void
language plpgsql security definer set search_path='' as $$
declare v_pessoa text; v_tarefa public.faxina_tarefas; v_agora timestamptz;
begin
 v_pessoa:=faxinas_private.minha_pessoa();
 if auth.uid() is null or v_pessoa is null then raise exception 'Acesso não autorizado.'; end if;
 if p_estado is null or p_estado not in ('concluida','nao_concluida') then raise exception 'Estado inválido.'; end if;
 select * into v_tarefa from public.faxina_tarefas where id=p_id for update;
 if not found or (v_tarefa.pessoa<>v_pessoa and v_pessoa<>'NAMOITA') then raise exception 'Tarefa não autorizada.'; end if;
 v_agora:=clock_timestamp();
 if v_agora>=v_tarefa.encerra_em and v_pessoa<>'NAMOITA' then raise exception 'Prazo encerrado. Somente NAMOITA pode corrigir.'; end if;
 update public.faxina_tarefas set estado=p_estado,
 multa_valor=case when p_estado='nao_concluida' and v_agora>=encerra_em then 30 else 0 end,
 alterada_em=v_agora,alterada_por=auth.uid() where id=p_id;
 insert into faxinas_private.auditoria(tarefa_id,usuario_id,estado_anterior,estado_novo)
 values(p_id,auth.uid(),v_tarefa.estado,p_estado);
end $$;
create or replace function public.faxina_marcar(p_id bigint,p_estado text) returns void
language sql security invoker set search_path='' as $$select faxinas_private.marcar(p_id,p_estado)$$;

-- Routines privadas com autorização explícita; wrappers públicos são INVOKER.
revoke all on function faxinas_private.liberar_acesso(text),faxinas_private.listar_acessos(),faxinas_private.listar(),faxinas_private.marcar(bigint,text) from public,anon;
grant execute on function faxinas_private.liberar_acesso(text),faxinas_private.listar_acessos(),faxinas_private.listar(),faxinas_private.marcar(bigint,text) to authenticated;
revoke all on function public.faxina_liberar_acesso(text),public.faxina_listar_acessos(),public.faxina_listar(),public.faxina_marcar(bigint,text) from public,anon;
grant execute on function public.faxina_liberar_acesso(text),public.faxina_listar_acessos(),public.faxina_listar(),public.faxina_marcar(bigint,text) to authenticated;

create or replace function faxinas_private.sincronizar(p_escalas jsonb) returns integer
language plpgsql security definer set search_path='' as $$
declare s record; p record; b text; tarefa text; n integer:=0;
begin
 for s in select * from jsonb_each(p_escalas) loop
  if s.key::date<date '2026-09-27' then continue; end if;
  for p in select * from jsonb_each(s.value->'pessoas') loop
   foreach b in array array['dom_seg_ter','qui_sex_sab'] loop
    tarefa:=btrim(p.value->>b);
    if tarefa is null or tarefa='' or upper(tarefa) in ('FOLGA','AUSENTE') then
     delete from public.faxina_tarefas where semana=s.key::date and pessoa=p.key and bloco=b and encerra_em>clock_timestamp() and estado='pendente';
     continue;
    end if;
    insert into public.faxina_tarefas(pessoa,semana,bloco,tarefa,encerra_em)
    values(p.key,s.key::date,b,tarefa,(s.key::date::timestamp + case b when 'dom_seg_ter' then interval '3 days' else interval '7 days' end) at time zone 'America/Sao_Paulo')
    on conflict(semana,pessoa,bloco) do update set tarefa=excluded.tarefa
    where public.faxina_tarefas.encerra_em>clock_timestamp() and public.faxina_tarefas.estado='pendente';
    n:=n+1;
   end loop;
  end loop;
 end loop;
 return n;
end $$;
create or replace function public.faxina_sincronizar_escalas(p_escalas jsonb) returns integer
language sql security invoker set search_path='' as $$select faxinas_private.sincronizar(p_escalas)$$;
revoke all on function faxinas_private.sincronizar(jsonb),public.faxina_sincronizar_escalas(jsonb) from public,anon,authenticated;
grant execute on function faxinas_private.sincronizar(jsonb),public.faxina_sincronizar_escalas(jsonb) to service_role;

-- Importação inicial da escala do ZIP (semanas anteriores são ignoradas).
select faxinas_private.sincronizar($escalas${
  "2026-09-06": {
    "atualizada_em": "06/09/2026",
    "pessoas": {
      "JUKEBOX": {
        "dom_seg_ter": "Área frontal da casa",
        "qui_sex_sab": "Cozinha"
      },
      "LOTERYA": {
        "dom_seg_ter": "Sala e copa",
        "qui_sex_sab": "Armários cozinha"
      },
      "KOMIXÃO": {
        "dom_seg_ter": "Cozinha",
        "qui_sex_sab": "FOLGA"
      },
      "NAMOITA": {
        "dom_seg_ter": "Geladeira",
        "qui_sex_sab": "Área traseira da casa"
      },
      "NAZARÉ": {
        "dom_seg_ter": "Lavanderia",
        "qui_sex_sab": "FOLGA"
      },
      "CAMILA": {
        "dom_seg_ter": "FOLGA",
        "qui_sex_sab": "Garagem"
      },
      "BAQUETADA": {
        "dom_seg_ter": "Panos",
        "qui_sex_sab": "Sala e copa"
      },
      "AMANDA": {
        "dom_seg_ter": "FOLGA",
        "qui_sex_sab": "FOLGA"
      },
      "BELA": {
        "dom_seg_ter": "FOLGA",
        "qui_sex_sab": "FOLGA"
      }
    }
  },
  "2026-09-13": {
    "atualizada_em": "13/09/2026 13:44",
    "pessoas": {
      "JUKEBOX": {
        "dom_seg_ter": "FOLGA",
        "qui_sex_sab": "Sala e copa"
      },
      "LOTERYA": {
        "dom_seg_ter": "FOLGA",
        "qui_sex_sab": "Garagem"
      },
      "KOMIXÃO": {
        "dom_seg_ter": "Panos",
        "qui_sex_sab": "Área traseira da casa"
      },
      "NAMOITA": {
        "dom_seg_ter": "Área frontal da casa",
        "qui_sex_sab": "FOLGA"
      },
      "NAZARÉ": {
        "dom_seg_ter": "Sala e copa",
        "qui_sex_sab": "Cozinha"
      },
      "CAMILA": {
        "dom_seg_ter": "Lavanderia",
        "qui_sex_sab": "Armários cozinha"
      },
      "BAQUETADA": {
        "dom_seg_ter": "Geladeira",
        "qui_sex_sab": "FOLGA"
      },
      "AMANDA": {
        "dom_seg_ter": "AUSENTE",
        "qui_sex_sab": "AUSENTE"
      },
      "BELA": {
        "dom_seg_ter": "Cozinha",
        "qui_sex_sab": "FOLGA"
      }
    }
  },
  "2026-09-20": {
    "atualizada_em": "19/09/2026 14:49",
    "pessoas": {
      "JUKEBOX": {
        "dom_seg_ter": "Panos",
        "qui_sex_sab": "FOLGA"
      },
      "LOTERYA": {
        "dom_seg_ter": "Geladeira",
        "qui_sex_sab": "FOLGA"
      },
      "KOMIXÃO": {
        "dom_seg_ter": "FOLGA",
        "qui_sex_sab": "Armários cozinha"
      },
      "NAMOITA": {
        "dom_seg_ter": "Cozinha",
        "qui_sex_sab": "FOLGA"
      },
      "NAZARÉ": {
        "dom_seg_ter": "FOLGA",
        "qui_sex_sab": "Garagem"
      },
      "CAMILA": {
        "dom_seg_ter": "FOLGA",
        "qui_sex_sab": "Área traseira da casa"
      },
      "BAQUETADA": {
        "dom_seg_ter": "Sala e copa",
        "qui_sex_sab": "FOLGA"
      },
      "AMANDA": {
        "dom_seg_ter": "Área frontal da casa",
        "qui_sex_sab": "Cozinha"
      },
      "BELA": {
        "dom_seg_ter": "Lavanderia",
        "qui_sex_sab": "Sala e copa"
      }
    }
  },
  "2026-09-27": {
    "atualizada_em": "27/09/2026 11:25",
    "pessoas": {
      "JUKEBOX": {
        "dom_seg_ter": "Sala e copa",
        "qui_sex_sab": "Cozinha"
      },
      "LOTERYA": {
        "dom_seg_ter": "Lavanderia",
        "qui_sex_sab": "FOLGA"
      },
      "KOMIXÃO": {
        "dom_seg_ter": "FOLGA",
        "qui_sex_sab": "Sala e copa"
      },
      "NAMOITA": {
        "dom_seg_ter": "Panos",
        "qui_sex_sab": "Área traseira da casa"
      },
      "NAZARÉ": {
        "dom_seg_ter": "Área frontal da casa",
        "qui_sex_sab": "FOLGA"
      },
      "CAMILA": {
        "dom_seg_ter": "Geladeira",
        "qui_sex_sab": "FOLGA"
      },
      "BAQUETADA": {
        "dom_seg_ter": "Cozinha",
        "qui_sex_sab": "FOLGA"
      },
      "AMANDA": {
        "dom_seg_ter": "FOLGA",
        "qui_sex_sab": "Garagem"
      },
      "BELA": {
        "dom_seg_ter": "FOLGA",
        "qui_sex_sab": "Armários cozinha"
      }
    }
  },
  "2026-10-04": {
    "atualizada_em": "27/09/2026 11:26",
    "pessoas": {
      "JUKEBOX": {
        "dom_seg_ter": "FOLGA",
        "qui_sex_sab": "Área traseira da casa"
      },
      "LOTERYA": {
        "dom_seg_ter": "Cozinha",
        "qui_sex_sab": "FOLGA"
      },
      "KOMIXÃO": {
        "dom_seg_ter": "Área frontal da casa",
        "qui_sex_sab": "FOLGA"
      },
      "NAMOITA": {
        "dom_seg_ter": "FOLGA",
        "qui_sex_sab": "Armários cozinha"
      },
      "NAZARÉ": {
        "dom_seg_ter": "Lavanderia",
        "qui_sex_sab": "Cozinha"
      },
      "CAMILA": {
        "dom_seg_ter": "Sala e copa",
        "qui_sex_sab": "FOLGA"
      },
      "BAQUETADA": {
        "dom_seg_ter": "Panos",
        "qui_sex_sab": "Sala e copa"
      },
      "AMANDA": {
        "dom_seg_ter": "Geladeira",
        "qui_sex_sab": "FOLGA"
      },
      "BELA": {
        "dom_seg_ter": "FOLGA",
        "qui_sex_sab": "Garagem"
      }
    }
  }
}$escalas$::jsonb);
-- Preserva confirmações antigas válidas; importação roda só em tarefas sem novo registro.
do $$
begin
 if to_regclass('public.confirmacoes') is not null then
  execute $import$update public.faxina_tarefas t set estado='concluida',multa_valor=0,alterada_em=c.concluida_em
   from public.confirmacoes c where t.pessoa=c.pessoa and t.semana=c.semana and t.tarefa=c.tarefa
   and t.bloco=case when c.bloco in ('DOM/SEG/TER','dom_seg_ter') then 'dom_seg_ter' else 'qui_sex_sab' end
   and c.concluida_em<t.encerra_em and t.alterada_em is null and t.estado='pendente'$import$;
 end if;
 if to_regclass('public.conclusoes') is not null then
  execute $import$update public.faxina_tarefas t set estado='concluida',multa_valor=0,alterada_em=c.concluida_em
   from public.conclusoes c where t.pessoa=c.pessoa and t.semana=c.semana and t.tarefa=c.tarefa and t.bloco=c.bloco
   and c.concluida_em<t.encerra_em and t.alterada_em is null and t.estado='pendente'$import$;
 end if;
end $$;

-- Fecha o antigo acesso sem senha. Dados históricos não são apagados.
do $$ declare r record; nome text; begin
 foreach nome in array array['confirmacoes','conclusoes','multas','profiles','perfis','atribuicoes'] loop
  if to_regclass('public.'||nome) is not null then
   execute format('revoke all on table public.%I from public,anon,authenticated',nome);
  end if;
 end loop;
 for r in select p.oid::regprocedure assinatura from pg_proc p join pg_namespace n on p.pronamespace=n.oid
 where n.nspname='public' and p.proname in ('confirmar_faxina','meu_nome','sou_admin','pessoa_do_usuario','usuario_e_admin') loop
  execute format('revoke all on function %s from public,anon,authenticated',r.assinatura);
 end loop;
end $$;
select faxinas_private.processar_vencidas();
notify pgrst,'reload schema';
commit;
